=== Soufiane-Chajjaoui/CourseXml/Schema/TP3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="EST">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="enseignant" type="Type_Enseignant" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="Type_Enseignant">
    <xs:sequence>
      <xs:element name="emails" type="Type_email" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="CIN" type="xs:string" use="required"/>
    <xs:attribute name="nom" type="xs:string" use="required"/>
    <xs:attribute name="prenom" type="xs:string" use="required"/>
    <xs:attribute name="sexe" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Homme"/>
          <xs:enumeration value="Femme"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  
  <xs:complexType name="Type_email">
    <xs:sequence>
      
      <xs:element name="emailAddress" type="xs:string" minOccurs="1" maxOccurs="unbounded">
      </xs:element>
      
    </xs:sequence>
    
    <xs:attribute name="typeMail">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="Academique"/>
          <xs:enumeration value="Personnel"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    
  </xs:complexType>
</xs:schema>

=== Soufiane-Chajjaoui/CourseXml/Schema/TP3.xml
<?xml version="1.0" encoding="UTF-8"?>
<EST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="TP3.xsd">
  <enseignant CIN="123456" nom="Doe" prenom="John" sexe="Homme">
    <emails>
      <emailAddress typeMail="Academique">john.doe@university.com</emailAddress>
      <emailAddress typeMail="Personnel">john.doe@gmail.com</emailAddress>
    </emails>
  </enseignant>
  <enseignant CIN="654321" nom="Smith" prenom="Jane" sexe="Femme">
    <emails>
      <emailAddress typeMail="Academique">jane.smith@university.com</emailAddress>
    </emails>
  </enseignant>
</EST>
